name: template
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  autoequal: ^0.3.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  sentry_flutter: ^6.3.0

dev_dependencies:
  auto_route_generator: ^3.2.3
  autoequal_gen: ^0.3.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.0.5
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
